build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "Pulsr.Window-win32/1.0"
    CONAN_LOGIN_USERNAME: "strootje"
    CONAN_USERNAME: "strootje"
    CONAN_CHANNEL: "conan"
    CONAN_REMOTES: "https://api.bintray.com/conan/conan-community/conan"
    CONAN_UPLOAD: "https://api.bintray.com/conan/strootje/conan"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15

install:
  - ps: wget https://cmake.org/files/v3.10/cmake-3.10.0-rc3-win64-x64.zip -OutFile cmake.zip
  - cmd: 7z x cmake.zip -o"C:\projects" -y > nul
  - set PATH=C:\projects\cmake-3.10.0-rc3-win64-x64\bin\;%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user

test_script:
  - python .conan/build.py
